Upgrade to SS4
silverstripe/platform-project pull request #30
Opened 2018-01-03 10:13 UTC by andrewandante

2018-01-03 12:51 UTC, dhensby requested changes

2018-01-03 12:51 UTC, dhensby commented on composer.json
> +		"phpunit/PHPUnit": "^5.7@stable"
lowercase ;)

2018-01-03 12:51 UTC, dhensby commented on composer.json
> +		"silverstripe/cms": "^4@stable",
You have `prefer-stable: true` set so you don't need the `@stable` flag here

2018-01-11 08:54 UTC, andrewandante commented
Ping @dhensby

2018-01-11 09:58 UTC, merged